### PR TITLE
Adding dir and table feature for console

### PR DESCRIPTION
**Pull request by VigneshMurugan**
Just felt we needed to add these two console properties as well

### CODE REVIEW

**Review by JAdshead — DISMISSED** [review]

**Review by Francois-Esquire — DISMISSED** [review]

**Comment by nellyk** [comment]
@VigneshMurugan Thank you for your contribution, could you please update the ReadMe to include the new features?

**Comment by VigneshMurugan** [comment]
> @VigneshMurugan Thank you for your contribution, could you please update the ReadMe to include the new features?

Done @nellyk

**Review by nellyk — APPROVED** [review]

**Comment by VigneshMurugan** [comment]
@Francois-Esquire @JAdshead Can you re review please? I updated the read me and the approval got revoked

**Review by JAdshead — APPROVED** [review]

**Comment by VigneshMurugan** [comment]
@nellyk Can you please merge this ?

**Comment by nellyk** [comment]
@VigneshMurugan thank you. Apologies for the delay. This has now been merged

**Pull request merged**
